//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinigent_ClientFeednback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_Client_Type
    {
        public ad_Client_Type()
        {
            this.ad_User = new HashSet<ad_User>();
        }
    
        public int Id { get; set; }
        public string ClientType { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ad_User> ad_User { get; set; }
    }
}
