//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinigent_ClientFeednback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_Rating
    {
        public ad_Rating()
        {
            this.bpo_Client_Feedback = new HashSet<bpo_Client_Feedback>();
            this.bpo_Client_Question_Rating_Settings = new HashSet<bpo_Client_Question_Rating_Settings>();
            this.cff_Client_Question_Rating_Settings = new HashSet<cff_Client_Question_Rating_Settings>();
        }
    
        public int Id { get; set; }
        public int Rating_Point { get; set; }
        public string Rating_Value { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<bpo_Client_Feedback> bpo_Client_Feedback { get; set; }
        public virtual ICollection<bpo_Client_Question_Rating_Settings> bpo_Client_Question_Rating_Settings { get; set; }
        public virtual ICollection<cff_Client_Question_Rating_Settings> cff_Client_Question_Rating_Settings { get; set; }
    }
}
