//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinigent_ClientFeednback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_User
    {
        public ad_User()
        {
            this.bpo_Client_Feedback = new HashSet<bpo_Client_Feedback>();
        }
    
        public string UserId { get; set; }
        public string UserPassword { get; set; }
        public int Client_Type_Id { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ad_Client_Type ad_Client_Type { get; set; }
        public virtual ICollection<bpo_Client_Feedback> bpo_Client_Feedback { get; set; }
    }
}
