//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinigent_ClientFeednback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bpo_Client_Questionaires
    {
        public bpo_Client_Questionaires()
        {
            this.bpo_Client_Feedback = new HashSet<bpo_Client_Feedback>();
            this.bpo_Client_Question_Rating_Settings = new HashSet<bpo_Client_Question_Rating_Settings>();
            this.Client_Question_Others = new HashSet<Client_Question_Others>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsOthers { get; set; }
    
        public virtual ICollection<bpo_Client_Feedback> bpo_Client_Feedback { get; set; }
        public virtual ICollection<bpo_Client_Question_Rating_Settings> bpo_Client_Question_Rating_Settings { get; set; }
        public virtual ICollection<Client_Question_Others> Client_Question_Others { get; set; }
    }
}
