//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinigent_ClientFeednback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cff_Client_Questionnaires
    {
        public cff_Client_Questionnaires()
        {
            this.cff_Client_Question_Rating_Settings = new HashSet<cff_Client_Question_Rating_Settings>();
            this.Client_Question_Others = new HashSet<Client_Question_Others>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public string Creator { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsOthers { get; set; }
    
        public virtual ICollection<cff_Client_Question_Rating_Settings> cff_Client_Question_Rating_Settings { get; set; }
        public virtual ICollection<Client_Question_Others> Client_Question_Others { get; set; }
    }
}
