//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinigent_ClientFeednback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Question_Others
    {
        public int Id { get; set; }
        public int Client_Question_Id { get; set; }
        public int RatingId { get; set; }
        public string Others { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual bpo_Client_Questionaires bpo_Client_Questionaires { get; set; }
        public virtual cff_Client_Questionnaires cff_Client_Questionnaires { get; set; }
    }
}
