//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infinigent_ClientFeednback.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qt_Infinigent_FeedbackEntities : DbContext
    {
        public qt_Infinigent_FeedbackEntities()
            : base("name=qt_Infinigent_FeedbackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ad_Client_Type> ad_Client_Type { get; set; }
        public DbSet<ad_Rating> ad_Rating { get; set; }
        public DbSet<ad_User> ad_User { get; set; }
        public DbSet<bpo_Client_Feedback> bpo_Client_Feedback { get; set; }
        public DbSet<bpo_Client_Question_Rating_Settings> bpo_Client_Question_Rating_Settings { get; set; }
        public DbSet<bpo_Client_Questionaires> bpo_Client_Questionaires { get; set; }
        public DbSet<cff_Client_Feedback> cff_Client_Feedback { get; set; }
        public DbSet<cff_Client_Question_Rating_Settings> cff_Client_Question_Rating_Settings { get; set; }
        public DbSet<cff_Client_Questionnaires> cff_Client_Questionnaires { get; set; }
        public DbSet<Client_Question_Others> Client_Question_Others { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
